In [1]:
# sym的本质是寻求一个最优的超平面，完成分类
# svm核： 若干个直线或曲线
# 身高体重 训练 预测

In [13]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

In [17]:
# 准备data
rand1 = np.array([[158,48],[159,50],[164,53],[168,56],[172,60]])
rand2 = np.array([[152,53],[156,55],[160,56],[172,64],[176,65]])
# clf = svm.SVC()
# clf.fit(np.vstack((rand1,rand2)),np.array([0,0,0,0,0,1,1,1,1,1]))
# clf.predict(np.array([[167,55],[162,57],[165,57]]))

array([0, 1, 1])

In [4]:
label = np.array([[0],[0],[0],[0],[0],[1],[1],[1],[1],[1]])
data = np.vstack((rand1,rand2))
data = np.array(data,dtype='float32')

In [5]:
label

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [11]:
# 训练
svm = cv2.ml.SVM_create() # ml 机器学习模块，创建一个svm
svm.setType(cv2.ml.SVM_C_SVC) # svm type
svm.setKernel(cv2.ml.SVM_LINEAR)
svm.setC(0.01)

result = svm.train(data,cv2.ml.ROW_SAMPLE,label)

# 预测
pt_data = np.vstack([[167,55],[162,57],[165,57]]) # 0,1
pt_data = np.array(pt_data,dtype=np.float32)
print(pt_data)
(par1,par2) = svm.predict(pt_data)
print(par1,'\n',par2)
print(type(par1))

[[167.  55.]
 [162.  57.]
 [165.  57.]]
0.0 
 [[0.]
 [1.]
 [1.]]
<class 'float'>
