## 步骤：

1. 卷积


In [8]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

# load data
mnist = input_data.read_data_sets('MNIST',one_hot=True)
trainImage = mnist.train.images[:500]
trainLabel = mnist.train.labels[:500]
testImage = mnist.test.images[:5]
testLabel = mnist.test.labels[:5]

Extracting MNIST\train-images-idx3-ubyte.gz
Extracting MNIST\train-labels-idx1-ubyte.gz
Extracting MNIST\t10k-images-idx3-ubyte.gz
Extracting MNIST\t10k-labels-idx1-ubyte.gz


In [14]:
# input
imageInput = tf.placeholder(tf.float32,[None,784])
labelInput = tf.placeholder(tf.float32,[None,10])

# 参数介绍 -1代表N张图片，28*28图片宽高，1代表一个通道。2D==>4D
imageInputReshape = tf.reshape(imageInput,[-1,28,28,1])

# 卷积 w0:卷积内核 5*5 output:32 in:1
w0 = tf.Variable(tf.truncated_normal([5,5,1,32],stddev=0.1))
# tf.random_normal()
# tf.truncated_normal() tf.truncated_normal的输出如字面意思是截断的，而截断的标准是2倍的stddev
b0 = tf.Variable(tf.constant(0.1,shape=[32]))


# layer1 
layer1 = tf.nn.relu(tf.nn.conv2d(imageInputReshape,w0,strides=[1,1,1,1],padding='SAME')+b0)
# pool 采样，数据量减小 batch*28*28*32 ==> batch*7*7*32
layer1_pool = tf.nn.max_pool(layer1,ksize=[1,4,4,1],strides=[1,4,4,1],padding="SAME")

# layer2 out 激励函数+乘加运算   softmax(激励函数+乘加运算)
w1 = tf.Variable(tf.truncated_normal([7*7*32,1024],stddev=0.1))
b1 = tf.Variable(tf.constant(0.1,shape=[1024]))

h_reshape = tf.reshape(layer1_pool,[-1,7*7*32]) # 平坦化
h1 = tf.nn.relu(tf.matmul(h_reshape,w1)+b1) # full connection

# softmax
w2 = tf.Variable(tf.truncated_normal([1024,10],stddev=0.1))
b2 = tf.Variable(tf.constant(0.1,shape=[10]))
pred = tf.nn.softmax(tf.matmul(h1,w2)+b2) # N*1024  1024*10 ==> N*10

# 损失函数计算方式，仅仅是误差概率求均值
loss0 = labelInput*tf.log(pred)
loss1 = 0
for m in range(100):
    for n in range(10):
        loss1 = loss1 + tf.abs(labelInput[m,n]-loss0[m,n])
loss = loss1/100

# train
train = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(100):
        sess.run(train,feed_dict={imageInput:trainImage,labelInput:trainLabel})
        pred_test = sess.run(pred,feed_dict={imageInput:testImage})
        print(np.argmax(pred_test,axis=1))
        print(np.argmax(testLabel,axis=1))
        print("===="*20)
#         pred_test = sess.run(pred,feed_dict={imageInput:images,labelInput:labels})
#         acc = tf.equal(tf.arg_max(pred_test,1),tf.arg_max(mnist.test.labels,1))
        
#         acc_float = tf.reduce_mean(tf.cast(acc,dtype=tf.float32))
#         acc_result = sess.run(acc_float,feed_dict={imageInput:mnist.test.images,labelInput:mnist.test.labels})
#         print(acc_result)


[4 4 4 3 3]
[7 2 1 0 4]
[4 4 4 8 8]
[7 2 1 0 4]
[4 4 4 1 8]
[7 2 1 0 4]
[4 4 4 1 8]
[7 2 1 0 4]
[4 4 4 6 8]
[7 2 1 0 4]
[4 4 4 6 8]
[7 2 1 0 4]
[4 6 4 6 8]
[7 2 1 0 4]
[4 6 1 6 4]
[7 2 1 0 4]
[4 6 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 6 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2

[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
[7 2 1 0 4]
