# placeholder

In [11]:
import tensorflow as tf
import numpy as np

In [4]:
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
dataAdd = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict={data1:[6,8],data2:[7,8]}))

[13. 16.]


### [[列数据],行[],...]  

In [5]:
[
 [1,2],
 [2,3],
 [4,5],
]

[[1, 2], [2, 3], [4, 5]]

In [6]:
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],
                     [3,4],
                     [5,6]])
print(data4.shape)

(3, 2)


In [7]:
with tf.Session() as sess:
    print(sess.run(data4))

[[1 2]
 [3 4]
 [5 6]]


## 矩阵运算

[矩阵运算图](http://p9tybni1b.bkt.clouddn.com/%E7%9F%A9%E9%98%B5%E8%BF%90%E7%AE%97.png)

In [16]:
matMul = tf.matmul(data1,data2)
matAdd = tf.add(data1,data3)
with tf.Session() as sess:
    print(sess.run(matMul)) # 一维
#     a = sess.run(data1)
#     b = sess.run(data2)
#     print(np.dot(a,b))
    print(sess.run(matAdd)) # 一行两列
    
    # 另一种方式
    print(sess.run([matMul,matAdd]))

[[24]]
[[9 9]]
[array([[24]]), array([[9, 9]])]


In [20]:
mat1 = tf.zeros((2,3),dtype=tf.int32)
mat2 = tf.ones((3,2),dtype=tf.int32)
mat3 = tf.fill((2,3),15)
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[15 15 15]
 [15 15 15]]


In [24]:
mat1 = tf.zeros((2,3),dtype=tf.int32)
mat2 = tf.zeros(mat1.shape)
mat3 = tf.linspace(1.0,2.0,11)
mat4 = tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[1.        1.1       1.2       1.3       1.4       1.5       1.6
 1.7       1.8       1.9000001 2.       ]
[[-0.07689846 -0.63873863 -0.4541433 ]
 [-0.3039292  -0.22477579  0.00877881]]
